name: Deploy EC2 monix-backend

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Call Deploy API
        env:
          SECRET: ${{ secrets.DEPLOY_EC2 }} # Variável de repositório configurada no painel do GitHub
        run: |
          curl -X POST "https://app.monixbr.com/deploy" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $SECRET"
